//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.chbase.thing.oxm.jaxb.sleepsessionv2;

import com.chbase.thing.oxm.jaxb.dates.Time;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
 * 			  A time and duration of an awakening during a period of&#13;
 * 			  sleep.&#13;
 * 			&lt;/summary&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;remarks xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
 * 			  An awakening covers those times during a sleep session&#13;
 * 			  in which the person awoke and then went back to sleep.&#13;
 * 			  For example, if a person wakes up during a night's&#13;
 * 			  sleep to use the restroom and then returns to sleep. It&#13;
 * 			  does not include awakenings that result in the person&#13;
 * 			  remaining awake for active periods.&#13;
 * 			&lt;/remarks&gt;
 * </pre>
 * 
 * <p>Java class for Awakening complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Awakening">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="when" type="{urn:com.microsoft.wc.dates}time"/>
 *         <element name="minutes" type="{urn:com.microsoft.wc.thing.types}nonNegativeInt"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Awakening", propOrder = {
    "when",
    "minutes"
})
public class Awakening {

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 				  The time when the person awoke.&#13;
     * 				&lt;/summary&gt;
     * </pre>
     * 
     */
    @XmlElement(required = true)
    protected Time when;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 				  The duration the person stayed awake in minutes.&#13;
     * 				&lt;/summary&gt;
     * </pre>
     * 
     */
    protected int minutes;

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 				  The time when the person awoke.&#13;
     * 				&lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Time }
     *     
     */
    public Time getWhen() {
        return when;
    }

    /**
     * Sets the value of the when property.
     * 
     * @param value
     *     allowed object is
     *     {@link Time }
     *     
     * @see #getWhen()
     */
    public void setWhen(Time value) {
        this.when = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 				  The duration the person stayed awake in minutes.&#13;
     * 				&lt;/summary&gt;
     * </pre>
     * 
     */
    public int getMinutes() {
        return minutes;
    }

    /**
     * Sets the value of the minutes property.
     * 
     */
    public void setMinutes(int value) {
        this.minutes = value;
    }

}
