//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.chbase.thing.oxm.jaxb.sleepsessionv2;

import com.chbase.thing.oxm.jaxb.base.CodableValue;
import com.chbase.thing.oxm.jaxb.dates.Time;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
 * 			  A phase in a person's sleep that includes the start time, duration, and the sleep state.&#13;
 * 			&lt;/summary&gt;
 * </pre>
 * 
 * <p>Java class for Level complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Level">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="start-time" type="{urn:com.microsoft.wc.dates}time" minOccurs="0"/>
 *         <element name="minutes" type="{urn:com.microsoft.wc.thing.types}nonNegativeInt"/>
 *         <element name="state" type="{urn:com.microsoft.wc.thing.types}codable-value"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Level", propOrder = {
    "startTime",
    "minutes",
    "state"
})
public class Level {

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 				  The time when this sleep state started.&#13;
     * 				&lt;/summary&gt;
     * </pre>
     * 
     */
    @XmlElement(name = "start-time")
    protected Time startTime;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 				  The duration the person stayed in this state.&#13;
     * 				&lt;/summary&gt;
     * </pre>
     * 
     */
    protected int minutes;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 				  The title of the sleep state.&#13;
     * 				&lt;/summary&gt;
     * </pre>
     * 
     */
    @XmlElement(required = true)
    protected CodableValue state;

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 				  The time when this sleep state started.&#13;
     * 				&lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link Time }
     *     
     */
    public Time getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Time }
     *     
     * @see #getStartTime()
     */
    public void setStartTime(Time value) {
        this.startTime = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 				  The duration the person stayed in this state.&#13;
     * 				&lt;/summary&gt;
     * </pre>
     * 
     */
    public int getMinutes() {
        return minutes;
    }

    /**
     * Sets the value of the minutes property.
     * 
     */
    public void setMinutes(int value) {
        this.minutes = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:ssv2="urn:com.microsoft.wc.thing.ssv2" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;&#13;
     * 				  The title of the sleep state.&#13;
     * 				&lt;/summary&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link CodableValue }
     *     
     */
    public CodableValue getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodableValue }
     *     
     * @see #getState()
     */
    public void setState(CodableValue value) {
        this.state = value;
    }

}
