//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.chbase.thing.oxm.jaxb.sleepsessionv2;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ssv2.thing.wc.microsoft.com package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ssv2.thing.wc.microsoft.com
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SleepSessionV2 }
     * 
     * @return
     *     the new instance of {@link SleepSessionV2 }
     */
    public SleepSessionV2 createSleepSessionV2() {
        return new SleepSessionV2();
    }

    /**
     * Create an instance of {@link Awakening }
     * 
     * @return
     *     the new instance of {@link Awakening }
     */
    public Awakening createAwakening() {
        return new Awakening();
    }

    /**
     * Create an instance of {@link Level }
     * 
     * @return
     *     the new instance of {@link Level }
     */
    public Level createLevel() {
        return new Level();
    }

}
