//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.chbase.thing.oxm.jaxb.bmi;

import com.chbase.thing.oxm.jaxb.base.DisplayValue;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;wrapper-class-name xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types" xmlns:wct="urn:com.microsoft.wc.types"&gt;BMIValue&lt;/wrapper-class-name&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types" xmlns:wct="urn:com.microsoft.wc.types"&gt;&#13;
 * 					BMI measurement.&#13;
 * 				&lt;/summary&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;remarks xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types" xmlns:wct="urn:com.microsoft.wc.types"&gt;&#13;
 * 					A BMI measurement consists of the value in kilograms per square                        metre,which is the base unit of measurement for BMI, and&#13;
 * 					an optional display value. The display value is used to&#13;
 * 					store the BMI measurement in the user's preference of&#13;
 * 					BMI units. This avoids rounding errors when&#13;
 * 					converting to and back from kilograms per square metre.&#13;
 * 				&lt;/remarks&gt;
 * </pre>
 * 
 * <p>Java class for bmi-value complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="bmi-value">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="kgm2" type="{urn:com.microsoft.wc.thing.types}nonNegativeDouble"/>
 *         <element name="display" type="{urn:com.microsoft.wc.thing.types}display-value" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bmi-value", propOrder = {
    "kgm2",
    "display"
})
public class BmiValue {

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types" xmlns:wct="urn:com.microsoft.wc.types"&gt;&#13;
     * 							The bmi measurement in kilograms per sq metre.&#13;
     * 						&lt;/summary&gt;
     * </pre>
     * 
     */
    protected double kgm2;
    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types" xmlns:wct="urn:com.microsoft.wc.types"&gt;&#13;
     * 							The display value for the bmi measurement.&#13;
     * 						&lt;/summary&gt;
     * </pre>
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;remarks xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types" xmlns:wct="urn:com.microsoft.wc.types"&gt;&#13;
     * 							The display value contains the bmi measurement&#13;
     * 							value stored in the user's preference of units.&#13;
     * 						&lt;/remarks&gt;
     * </pre>
     * 
     */
    protected DisplayValue display;

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types" xmlns:wct="urn:com.microsoft.wc.types"&gt;&#13;
     * 							The bmi measurement in kilograms per sq metre.&#13;
     * 						&lt;/summary&gt;
     * </pre>
     * 
     */
    public double getKgm2() {
        return kgm2;
    }

    /**
     * Sets the value of the kgm2 property.
     * 
     */
    public void setKgm2(double value) {
        this.kgm2 = value;
    }

    /**
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types" xmlns:wct="urn:com.microsoft.wc.types"&gt;&#13;
     * 							The display value for the bmi measurement.&#13;
     * 						&lt;/summary&gt;
     * </pre>
     * 
     *             
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;remarks xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types" xmlns:wct="urn:com.microsoft.wc.types"&gt;&#13;
     * 							The display value contains the bmi measurement&#13;
     * 							value stored in the user's preference of units.&#13;
     * 						&lt;/remarks&gt;
     * </pre>
     * 
     * @return
     *     possible object is
     *     {@link DisplayValue }
     *     
     */
    public DisplayValue getDisplay() {
        return display;
    }

    /**
     * Sets the value of the display property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayValue }
     *     
     * @see #getDisplay()
     */
    public void setDisplay(DisplayValue value) {
        this.display = value;
    }

}
