//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.03 at 08:13:20 PM PST 
//

package com.chbase.methods.jaxb.getpeopleforrecord.request;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

import com.chbase.methods.jaxb.JaxbRequest;

@JaxbRequest(methodName = "GetPeopleForRecord", methodVersion = "1", responseNS = "urn:com.microsoft.wc.methods.response.GetPeopleForRecord")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {})
@XmlRootElement(name = "info")
public class GetPeopleForRecordRequest {

}
